version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/church_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: church_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password